// AUTO-GENERATED by zedu-egret-store — do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

import type { Metadata } from "next";

import { contributorCount, contributors } from "./index";

export const metadata: Metadata = {
  title: "Zedu Egret Contributors",
  description:
    "Contributors who have completed Stage 1 verification in the Zedu Egret internship.",
  alternates: {
    canonical: "/contributors",
  },
};

const ContributorsPage = () => {
  return (
    <section className="mt-12">
      <div className="mx-auto w-full max-w-5xl px-4 pb-16 sm:px-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-700">
          Zedu Egret
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900">
          Contributors
        </h1>
        <p className="mt-2 text-sm text-gray-600">
          Everyone who has completed Stage 1 verification.
          {contributorCount > 0
            ? ` ${contributorCount} contributor${contributorCount === 1 ? "" : "s"} so far.`
            : " No contributors yet."}
        </p>

        {contributorCount === 0 ? (
          <p className="mt-8 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-600">
            No contributors yet. Complete Stage 1 to be the first on this list.
          </p>
        ) : (
          <ol className="mt-8 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
            {contributors.map((contributor, index) => (
              <li
                key={`${contributor.name}-${index}`}
                className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"
              >
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-800">
                  {index + 1}
                </span>
                <span className="truncate text-sm font-semibold text-gray-900">
                  {contributor.name}
                </span>
              </li>
            ))}
          </ol>
        )}
      </div>
    </section>
  );
};

export default ContributorsPage;
