// AUTO-GENERATED by zedu-egret-store - do not edit by hand.
// Regenerated on every verified Stage 1 submission (GitHub Action).

export type Contributor = {
  name: string;
  repo: string;
};

export const contributors: Contributor[] = [
  { name: "AbdulJaleel AbdulSamad", repo: "https://github.com/TrippleA001/hng_task_1_todo_app" },
  { name: "Abdullateef Dauda", repo: "https://github.com/abdul-o/todo-app" },
  { name: "Adejumoke Oluwole", repo: "https://github.com/jumokeolu/Todo-list-app" },
  { name: "Aisha Abdulkadir Joda", repo: "https://github.com/jodaaisha2-blip/To-do-app" },
  { name: "Akinremi Oluwatoyin Mary", repo: "https://github.com/Oluwatoyin-224/Listflow" },
  { name: "Babatunde Omojuwa", repo: "https://github.com/juskins/Taskly" },
  { name: "Bilkis Oladimeji", repo: "https://github.com/Atete22/hng_project" },
  { name: "Bolakale Fuad", repo: "https://github.com/bolakale6/todo-app" },
  { name: "Christiana Mabel Nyuma", repo: "https://github.com/Mabel007/hng-todo" },
  { name: "Chukwuebuka Okonta", repo: "https://github.com/devEbuka/HNG_blueprint" },
  { name: "Chukwumaeze Henry Chinaemerem", repo: "https://github.com/Henrycalebz0/todo-list" },
  { name: "Dolapo Ewulogbo", repo: "https://github.com/DolapoEwulogbo/InQueue" },
  { name: "Ekwere Noble Nathan", repo: "https://github.com/ENJ0Y-Labs/todo-list" },
  { name: "Elizabeth Oluwatobi David", repo: "https://github.com/apptaster123-hash/MiraiTasks" },
  { name: "EMMANUEL EFFIONG", repo: "https://github.com/Solutionsboxx/zedu" },
  { name: "Emmanuel Matthew Ekanem", repo: "https://github.com/AnalytiqDigital/todoApp" },
  { name: "Fatimat Titilayo Mufutau", repo: "https://github.com/pharteey/Urghency" },
  { name: "Favour Chinaza", repo: "https://github.com/favourchinaza110/hng-to-do-list" },
  { name: "Fawaz Yusuff", repo: "https://github.com/flawrrz/hng-i15-stage-1-todo-list" },
  { name: "Francis Anyah", repo: "https://github.com/assisi-francis/todo_list" },
  { name: "Godgift Achong", repo: "https://github.com/giftninho/HNG_taskflow-todo" },
  { name: "Ibrahim Sulaimon Opeyemi", repo: "https://github.com/Sulai007/HNG-todo-app" },
  { name: "Jalar Jacques", repo: "https://github.com/jalarjacques-gif/HNG-TASK-1" },
  { name: "Joanna Tebadda", repo: "https://github.com/JoannaTebadda/zuratasks" },
  { name: "Jonathan Gomina", repo: "https://github.com/jonathan401/HNG-todolist" },
  { name: "Kafayat Faniran", repo: "https://github.com/KaffyDevelops/CustomWidgetCreator_Plugin" },
  { name: "Manu Jesse", repo: "https://github.com/Manu2232/to-dolist-app" },
  { name: "Michelle Utomi", repo: "https://github.com/michycipher/dayflow-todo" },
  { name: "Mutairu Dirisu", repo: "https://github.com/mutairudirisu/onWard" },
  { name: "Nduaguba Marcellus", repo: "https://github.com/creativemcn/Mcntodo" },
  { name: "Okeke Chukwuebuka", repo: "https://github.com/OKEKE-PRINCEWILL/Hng_todo_app" },
  { name: "Okolie Chinonso Grace", repo: "https://github.com/chinonsograce/little-list" },
  { name: "Olatunji Mafe", repo: "https://github.com/toondji-ix/TASKone" },
  { name: "Olayeni Ibrahim", repo: "https://github.com/Oluwa555/todo-list-app" },
  { name: "Oluboye Adekunle", repo: "https://github.com/Boyeadelo/dojuko-todo-app" },
  { name: "Onatade Abdulmajeed Adeyincka", repo: "https://github.com/Spider1201/todo-list-hng" },
  { name: "Precious Nse", repo: "https://github.com/preshnse-code/To-do-list" },
  { name: "Precious Nse Samuel", repo: "https://github.com/EmkaySOL/Hng-Todo-App" },
  { name: "Preshnat", repo: "https://github.com/presh27/My-Taskly" },
  { name: "Rukayyah Ibrahim", repo: "https://github.com/iamadoctorforreal/HNG15-Stage-0-ToDo-List" },
  { name: "Samson Eyitene", repo: "https://github.com/eyisam/Hng-Todo-list" },
  { name: "Samuel Olowu", repo: "https://github.com/samuelolowu-ET-hue/todoflow" },
  { name: "TIENTCHEU WONSI DILANE", repo: "https://github.com/TientcheuWonsiDilane/HNG_Stage1" },
  { name: "Victor Tommy Etudor", repo: "https://github.com/victoretudor/taskflow-todo-app" },
];

export const contributorCount = contributors.length;

export default contributors;
